name: Maven Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # 使用 Temurin 作为 Java 的分发版本
          java-version: '11'       # 指定使用 Java 11 版本

      - name: Run Maven build
        run: mvn clean test
